### ISSUE TITLE
Removed from Ansible Galaxy?

### ISSUE THREAD

**Issue by kimamula** [singleplatform-eng/ansible-users#49]
The following page returns 404.

https://galaxy.ansible.com/mivok0/users/

Is this role no longer published in Ansible Galaxy?

**Comment by mgla** [comment]
+1

**Comment by bitfoo1** [comment]
+1

**Comment by ghost** [comment]
Oops, didn't mean to close this.

@mivok [transferred ownership](https://github.com/singleplatform-eng/ansible-users/issues/30) of the ansible-users repo back in November 2016. After doing so, the mivok0 galaxy link continued to work which seemed like a good thing.

However, due to [this issue](https://github.com/ansible/galaxy-issues/issues/247) I had to delete and re-add the role in galaxy in order to import any new releases. After deleting and re-adding the role, the mivok0 link ceased to exist. Apologies if this caused any trouble/confusion.

The correct link is now https://galaxy.ansible.com/singleplatform-eng/users/.

**Comment by kimamula** [comment]
I see, thanks!

**Comment by kcd83** [comment]
I see this is now
https://galaxy.ansible.com/singleplatform_eng/users
or `singleplatform_eng.users` with an `_` instead of a `-`
